export const CONSTANTS = {
  ID: '#ID',
  REGEX_NOT_ONLY_EMPTY_SPACES: /(.|\s)*\S(.|\s)*/,
  MIN_LENGTH: 3,
  INITIAL_PAGE: 1,
  LIMIT_PER_PAGE: 6,
  MINIMUM_SEARCH_CHARACTERS: 3,
  NO_RESEARCH: '',
}
